### ISSUE TITLE
App crash if upload.wikimedia.org is unreachable

### ISSUE THREAD

**Issue by licaon-kter** [babydots/babybook#1]
https://github.com/babydots/babybook/commit/a1580206ad38c25db2bd06d4bc2fc3673218e5e8 selfbuilt

```
FATAL EXCEPTION: main
Process: com.serwylo.babybook, PID: 32702
io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://upload.wikimedia.org/wikipedia/commons/xxxx/xxxx/xxxxx.jpg, connect_timeout=unknown ms]
	at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:183)
	at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:180)
	at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:240)
	at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:232)
	at io.ktor.client.engine.cio.Endpoint.access$connect(Endpoint.kt:28)
	at io.ktor.client.engine.cio.Endpoint$connect$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by pserwylo** [comment]
Although I didn't reproduce this specific exception, I can see there is no exception handling at all around any of the wikipedia communication. I've added some rudimentary catch blocks which show a little toast message saying "An error occurred communicating with Wikipedia. Are you connected to the internet?". In the future this should be enhanced to be more user friendly.

**Comment by licaon-kter** [comment]
Netguard, try to add a book, allow simple.wikipedia.org, select a topic...
